nohup: ignoring input
*********************************Move to SABEV directory*********************************
*********************************build*********************************
sparsebev_train.sh: line 11: /home/hathwar/miniconda/etc/profile.d/conda.sh: No such file or directory
sparsebev_train.sh: line 12: conda: command not found
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: http://pypi-cache/index
Requirement already satisfied: fvcore in /home/hathwar/.local/lib/python3.10/site-packages (0.1.5.post20221221)
Requirement already satisfied: numpy in /home/hathwar/.local/lib/python3.10/site-packages (from fvcore) (2.2.1)
Requirement already satisfied: yacs>=0.1.6 in /home/hathwar/.local/lib/python3.10/site-packages (from fvcore) (0.1.8)
Requirement already satisfied: pyyaml>=5.1 in /home/hathwar/.local/lib/python3.10/site-packages (from fvcore) (6.0.2)
Requirement already satisfied: tqdm in /home/hathwar/.local/lib/python3.10/site-packages (from fvcore) (4.65.2)
Requirement already satisfied: termcolor>=1.1 in /home/hathwar/.local/lib/python3.10/site-packages (from fvcore) (3.1.0)
Requirement already satisfied: Pillow in /home/hathwar/.local/lib/python3.10/site-packages (from fvcore) (11.1.0)
Requirement already satisfied: tabulate in /home/hathwar/.local/lib/python3.10/site-packages (from fvcore) (0.9.0)
Requirement already satisfied: iopath>=0.1.7 in /home/hathwar/.local/lib/python3.10/site-packages (from fvcore) (0.1.10)
Requirement already satisfied: typing-extensions in /home/hathwar/.local/lib/python3.10/site-packages (from iopath>=0.1.7->fvcore) (4.12.2)
Requirement already satisfied: portalocker in /home/hathwar/.local/lib/python3.10/site-packages (from iopath>=0.1.7->fvcore) (3.1.1)
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: http://pypi-cache/index
Requirement already satisfied: einops in /home/hathwar/.local/lib/python3.10/site-packages (0.8.1)
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: http://pypi-cache/index
Requirement already satisfied: iopath in /home/hathwar/.local/lib/python3.10/site-packages (0.1.10)
Requirement already satisfied: tqdm in /home/hathwar/.local/lib/python3.10/site-packages (from iopath) (4.65.2)
Requirement already satisfied: typing-extensions in /home/hathwar/.local/lib/python3.10/site-packages (from iopath) (4.12.2)
Requirement already satisfied: portalocker in /home/hathwar/.local/lib/python3.10/site-packages (from iopath) (3.1.1)
*********************************training model*********************************
False
sparsebev_train.sh: line 20: nvidia-smi: command not found

W0608 22:40:16.204000 3880753 torch/distributed/run.py:793] 
W0608 22:40:16.204000 3880753 torch/distributed/run.py:793] *****************************************
W0608 22:40:16.204000 3880753 torch/distributed/run.py:793] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
W0608 22:40:16.204000 3880753 torch/distributed/run.py:793] *****************************************
Traceback (most recent call last):
  File "/netscratch/kpatil/SparseBEV/SparseBEV7_Radar_S5_withNeck/train.py", line 2, in <module>
    import utils
  File "/netscratch/kpatil/SparseBEV/SparseBEV7_Radar_S5_withNeck/utils.py", line 8, in <module>
Traceback (most recent call last):
  File "/netscratch/kpatil/SparseBEV/SparseBEV7_Radar_S5_withNeck/train.py", line 2, in <module>
    from mmcv.runner.hooks import HOOKS
ModuleNotFoundError: No module named 'mmcv'
    import utils
  File "/netscratch/kpatil/SparseBEV/SparseBEV7_Radar_S5_withNeck/utils.py", line 8, in <module>
    from mmcv.runner.hooks import HOOKS
ModuleNotFoundError: No module named 'mmcv'
Traceback (most recent call last):
  File "/netscratch/kpatil/SparseBEV/SparseBEV7_Radar_S5_withNeck/train.py", line 2, in <module>
    import utils
  File "/netscratch/kpatil/SparseBEV/SparseBEV7_Radar_S5_withNeck/utils.py", line 8, in <module>
    from mmcv.runner.hooks import HOOKS
ModuleNotFoundError: No module named 'mmcv'
Traceback (most recent call last):
  File "/netscratch/kpatil/SparseBEV/SparseBEV7_Radar_S5_withNeck/train.py", line 2, in <module>
    import utils
  File "/netscratch/kpatil/SparseBEV/SparseBEV7_Radar_S5_withNeck/utils.py", line 8, in <module>
    from mmcv.runner.hooks import HOOKS
ModuleNotFoundError: No module named 'mmcv'
W0608 22:40:17.715000 3880753 torch/distributed/elastic/multiprocessing/api.py:897] Sending process 3880770 closing signal SIGTERM
E0608 22:40:17.747000 3880753 torch/distributed/elastic/multiprocessing/api.py:869] failed (exitcode: 1) local_rank: 1 (pid: 3880771) of binary: /usr/bin/python3
Traceback (most recent call last):
  File "/home/hathwar/.local/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/hathwar/.local/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 355, in wrapper
    return f(*args, **kwargs)
  File "/home/hathwar/.local/lib/python3.10/site-packages/torch/distributed/run.py", line 919, in main
    run(args)
  File "/home/hathwar/.local/lib/python3.10/site-packages/torch/distributed/run.py", line 910, in run
    elastic_launch(
  File "/home/hathwar/.local/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 138, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/hathwar/.local/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 269, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2025-06-08_22:40:17
  host      : virt-3326.kl.dfki.de
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 3880772)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2025-06-08_22:40:17
  host      : virt-3326.kl.dfki.de
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 3880773)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2025-06-08_22:40:17
  host      : virt-3326.kl.dfki.de
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 3880771)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
*********************************testing model*********************************
